services:
  web: # This service defines the Odoo container.
    image: ${ODOO_IMAGE} # Uses the official Odoo version 17.0 image.
    restart: unless-stopped
    env_file:
      - .env
    depends_on: # Specifies dependencies. The 'web' service will only start after the 'db' service is active.
      - db
    ports:
      - "${WEB_PORT}:${WEB_DEFAULT_PORT}"
      - "${DEBUGPY_PORT}:${DEBUGPY_PORT}"
    volumes:
      - odoo-v17-web-data:/var/lib/odoo # Mounts a persistent volume for Odoo data.
      - ./config:/etc/odoo # Mounts custom configuration files from your local machine to the container.
      - ./addons:/mnt/extra-addons # Mounts the folder for custom addons.
      - ./log:/var/log/odoo # Mounts the log folder so you can view logs locally.
      - ./requirements.txt:/requirements.txt # Monta el archivo requirements.txt dentro del
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password # Specifies the location of the file containing the database password.
    secrets:
      - postgresql_password # Defines a secret that will be passed securely to the container.
    entrypoint: ${entrypoint}

  db: # This service defines the PostgreSQL container.
    image: ${DB_IMAGE} # Uses the official PostgreSQL version 15 image.
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME} # The default database name that will be created.
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password # Specifies the location of the file containing the database password.
      - POSTGRES_USER=${DB_USER} # Defines the PostgreSQL user as 'odoo'.
      - PGDATA=/var/lib/postgresql/data/pgdata # Specifies the location of the PostgreSQL data directory.
    volumes:
      - odoo-v17-db-data:/var/lib/postgresql/data/pgdata # Mounts a persistent volume for database data.
    secrets:
      - postgresql_password # Defines a secret that will be passed securely to the container.

volumes:
  odoo-v17-web-data:
    name: odoo_v17_web_data_volume_work # Defines a persistent volume with a specific name for Odoo data.
  odoo-v17-db-data:
    name: odoo_v17_db_data_volume_work # Defines a persistent volume with a specific name for PostgreSQL data.

secrets:
  postgresql_password:
    file: odoo_pg_pass # Specifies the location of the secret file containing the database password.

name: ${DOCKER_NAME} # The name of the configuration, useful for identifying this specific project.
